### ISSUE TITLE
Goed dat je stylesheet gebruikt, classes meer toepaasen

### ISSUE THREAD

**Issue by lisagjh** [kimnikitaschijf/look-and-feel-corporate-identity#29]
https://github.com/kimnikitaschijf/look-and-feel-corporate-identity/blob/54ec704507ada61dd921d1aa3f57c9f6264cc9d0/home.html#L8

Goed dat je de gedeelde stylesheet hebt gelinkt!

Hier pas je de stylesheet goed toe:

https://github.com/kimnikitaschijf/look-and-feel-corporate-identity/blob/54ec704507ada61dd921d1aa3f57c9f6264cc9d0/styles/styles.css#L58-L59

Een goede volgende stap zou zijn om te kijken hoe je de classes meer kunt gaan gebruiken in jouw html. Zijn de classes in de stylesheet te specifiek of te algemeen?

Verder ziet het er prima uit, goed bezig!

**Comment by kimnikitaschijf** [comment]
Ik heb gebruik gemaakt van de .color class van de gedeelde stylesheet. Dit is te zien in issue #28 van mij :)
