### ISSUE TITLE
Media queries toegevoegd aan code

### ISSUE THREAD

**Issue by kimnikitaschijf** [kimnikitaschijf/look-and-feel-corporate-identity#31]
### Home pagina:
https://github.com/kimnikitaschijf/look-and-feel-corporate-identity/blob/main/home.css#L309-L382

### Groene bieb pagina:
https://github.com/kimnikitaschijf/look-and-feel-corporate-identity/blob/main/styles/styles.css#L268-L335

**Comment by lemuelmgsn** [comment]
## klein tipje!

Je kan een met een "permalink " een kleine preview van je code in je issue laten zien.

Dit doe je door de code lijnen te selecteren, daarna op de 3 stipjes te klikken en vervolgens op "copy permalink"

### Foto

![image](https://github.com/user-attachments/assets/40735910-c995-4c30-a1f9-a7e0f603c7be)

Deze permalink plak je dan hier in je issue, dit ziet er dan zo uit:

https://github.com/kimnikitaschijf/look-and-feel-corporate-identity/blob/4fb1f689b926c1301231c20e299a5ffd5e4da3ad/home.css#L309-L382

https://github.com/kimnikitaschijf/look-and-feel-corporate-identity/blob/4fb1f689b926c1301231c20e299a5ffd5e4da3ad/styles/styles.css#L268-L335
